name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWI5MTc3ZmMtZmI5OS00NTE3LWIwZDMtMmNlNTE2MGViOTA0IiwidGVuYW50X2lkIjoiNWU1ODkwODlmZmVlYThmYzBjNjFjYTZiZjljMDNiMTI3OGYzOTBmMDM0YjAwYTJjMWY1NDg2MzE2MjVmMzQ1MSIsImludGVybmFsX3NlY3JldCI6IjExYjZlNzVjLWNlNTktNDUyNy04ZmM2LTExZWVkN2M2YTU2MyJ9.ECPeRN3KuITd8OPQuzbz7o3TWC7jNeTUdmHa7MJ3hDk"
JWT_SECRET = "prakashisGOATzmzmz"